### ISSUE TITLE
反馈在Firefox和Opera无法播放声音

### ISSUE THREAD

**Issue by onexuan** [gera2ld/h5player#2]
东西很好，我测试了几种浏览器，在Firefox和Opera无法播放声音，能否修复一下？

**Comment by gera2ld** [comment]
我测试正常啊，能否提供下操作系统和版本号？

**Comment by onexuan** [comment]
谢谢这么快回馈
Opera V30.0.1835.88
Firefox V41.0.1

我是两个版本都无法播放MP3，只能播放Ogg文件，查了网上资料，说是HTML5这两个浏览器是无法播放MP3的。

**Comment by onexuan** [comment]
刚才再测试http://gerald.top/code/h5player 你这个地址，无法播放声音的！

**Comment by gera2ld** [comment]
我的页面我测试都没有问题啊，如果是浏览器不支持我也没有办法的。。

**Comment by gera2ld** [comment]
我测试了mac、ubuntu、win10下的opera、chrome、firefox最新版，结果只有ubuntu+opera不能播放，而这种情况下网易云音乐也用不了，感觉opera在linux下本来就很多问题。。
另外这个播放器只是提供一个界面而已，真正的播放功能还是需要浏览器本身支持的，如果浏览器不能支持那也没有办法。
